### ISSUE TITLE
 Download system dependencies in the opencontrol.yaml

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry-go#6]
GIVEN system dependencies in the opencontrols.yaml, WHEN the `masonry get` command is run, THEN the masonry cli downloads the controls the system dependencies point at and places each in the `opencontrols/components`.

```yaml
system_name: Analytics Reporter
system_key: Analytics-Reporter
components:
  - ./information-system-documentation
  - ./static-analysis
  - ./vulnerability-scanning
dependencies:  # Issue 6 pertains to this object
  certification: github.com/18F/LATO
  systems:
    - github.com/18F/cg-complinace
  standards:
    - standard: github.com/18F/NIST-800-53

```
