### ISSUE TITLE
Allow components to be exported when listed in opencontrols.yaml

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry-go#7]
Given an `opencontrols.yaml` file that points to another opencontrols.yaml file WHEN `masonry get` is run THEN components listed in the pointed to `opencontrols.yaml` under the `components` object are also downloaded and placed under the `opencontrols/components/` dir.

related to #6 

```yaml
system_name: Analytics Reporter
system_key: Analytics-Reporter
components: # Issue 7 pertains to this object
  - ./information-system-documentation
  - ./static-analysis
  - ./vulnerability-scanning
dependencies:
  certification: github.com/18F/LATO
  systems:
    - github.com/18F/cg-complinace
  standards:
    - standard: github.com/18F/NIST-800-53

```
