### ISSUE TITLE
Download certifications and standards 

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry-go#8]
Given certification and standards in the dependencies, WHEN the masonry get command is run, THEN the standards and certification and downloaded into the `opencontrols/` directory. 
```yaml
system_name: Analytics Reporter
system_key: Analytics-Reporter
components:
  - ./information-system-documentation
  - ./static-analysis
  - ./vulnerability-scanning
dependencies:
  certification: github.com/18F/LATO
  systems: # issue 8
    - github.com/18F/cg-complinace
  standards: # issue 8
    - standard: github.com/18F/NIST-800-53
```
